import { ModalProvider } from "@/context/ModalContext";
import SurveyModal from "@/ui/SurveyModal";
import sfCompact from "@/lib/fonts";
import "@/styles/app.scss";
import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={sfCompact.variable}>
      {/* Font Awesome CDN */}
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/js/all.min.js" />

      <body>
        <ModalProvider>
          {children}
          <SurveyModal />
        </ModalProvider>
      </body>
    </html>
  );
}
